name: Build macOS Portable x64

on:
  workflow_dispatch:

jobs:
  build-mac-portable:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build macOS app
        run: npx electron-builder --mac dir --x64 --publish never

      - name: Zip app
        run: |
          cd dist/mac
          ditto -c -k --sequesterRsrc --keepParent CraftLauncher.app ../CraftLauncher-mac-portable-x64.zip

      - name: Upload portable app
        uses: actions/upload-artifact@v4
        with:
          name: craftlauncher-mac-portable-x64
          path: dist/CraftLauncher-mac-portable-x64.zip
